### ISSUE TITLE
plugin/library idea: parsers and/or sniffers for common bioinformatics file formats

### ISSUE THREAD

**Issue by ihh** [evoldoers/biomake#16]
It would be useful to be able to auto-detect file formats in a Makefile, and condition the rules on the formats of the files rather than just relying on the filenames.

this could be achieved by including a library of parsers for standard formats (GFF, FASTA, Newick, etc). some of these are already in blipkit...

of course, parsing a big file every time it tried to match a rule would probably make Biomake grind to a halt. maybe there is a way to optimize it though - e.g. storing as metadata in the `.biomake` directory.

**Comment by cmungall** [comment]
Those parsers are fairly old.

For sniffing I think it's best to have lightweight scripts written in any language that parse the first N lines for tell-tale signatures. AFAICR this is how galaxy works.

**Comment by ihh** [comment]
It's possible to implement those kind of sniffers in prolog and they could be attached using the new post-dependency prolog hook, though I've come to think this is probably not all that useful an idea. Most of the time, with makefiles, you know the format from the filename suffix - that's kind of the point.

**Comment by ihh** [comment]
see also #21 which would make it a little cumbersome to implement these sniffers in the prolog/endprolog block.
