### ISSUE TITLE
Inclusion of phony targets, and more informative error messages.

### ISSUE THREAD

**Issue by mahesh-panchal** [evoldoers/biomake#29]
Hi,

I'm trying to make a more practical workflow to test, but would like the inclusion of PHONY targets
```
# Programs
APP_FASTQC='/sw/apps/bioinfo/fastqc/0.11.5/milou/fastqc'
APP_KRAKEN='/sw/apps/bioinfo/Kraken/0.10.5-beta/milou/kraken'
APP_KAT='/sw/apps/bioinfo/KAT/2.1.1/milou/bin/kat'
DB_KRAKEN='/sw/data/uppnex/Kraken/latest'
# Filenames
FASTQ_FILES = bacteria_Str1_R1.fastq  bacteria_Str1_R2.fastq
FASTQC_FILES = $(FASTQ_FILES:.fastq=_fastqc.html)

fastqc : ${FASTQC_FILES}
        @echo "FastQC completed on all files"

%_fastqc.html : %.fastq
        @echo "FastQC -> $^"
        $(APP_FASTQC) -t 6 $^ 
```
When trying `biomake fastqc` I just get the message
fastqc FAILED
Could a more informative error message be given please?

Also when trying `biomake -d fastqc`, I don't know whether `-d` isn't working or if the error doesn't have a message.
```
Warning: verbose: no matching debug topic (yet)
fastqc FAILED
```
Regards,
Mahesh.

**Comment by cmungall** [comment]
I opened a PR for the spurious warnings.

Am investigating the main issue. I think there may be two issues:


when this is executed:

```
FASTQC_FILES = $(FASTQ_FILES:.fastq=_fastqc.html)
```

it looks like only the final element of the list is substituted.

Additionally, it looks like `${VAR}` is not working in the dependency position. You should be able to substitute this with `$(VAR)` for the same results.

Will try and look in more detail shortly

**Comment by ihh** [comment]
I have fixed the two issues mentioned by @cmungall, i.e. the `${VAR}` parse failure (was being confused with a Prolog goal) and the failure of substitution references to work with lists. We still don't have .PHONY (although phony targets _per se_ should work, as with the `fastq` target in your Makefile @mahesh-panchal ) and I agree the error messages could be better (although `-d` now turns on `--debug build` by default, which gives a bit more info).

**Comment by ihh** [comment]
Latest commit adds a more informative error message when biomake doesn't know how to build a target.

**Comment by ihh** [comment]
As one more footnote: phony targets were always supported, it was the `.PHONY` special target that wasn't. As of now, it is. Thank you @mahesh-panchal for your excellent feedback
