### ISSUE TITLE
Prevent "no matching debug topic (yet)" messages

### ISSUE THREAD

**Issue by ihh** [evoldoers/biomake#31]
e.g. running `biomake -d` in a directory without a Makefile gives 

~~~~
Warning: verbose: no matching debug topic (yet)
Warning: build: no matching debug topic (yet)
No Makefile found
~~~~

Looking at the source for `debug/1`, linked below, it seems like it's always going to print a message. Guess we could write our own version of `debug`.

http://www.swi-prolog.org/pldoc/doc/swi/library/debug.pl?show=raw

**Comment by cmungall** [comment]
It would be a shame to write our own; even though it would be simple, it's nice having a unified mechanism for the case where we may want to combine external prolog programs with debug directives into the rulebase for a makefile.

There are a few things we can try. It should be possible to intercept messages. But first have a look at the PR I'm about to do that 'declares' debug topics as a top-level directive. See also my comments here: http://eu.swi-prolog.org/pldoc/man?predicate=debug/1

For this strategy we have an option of doing this modularly, with each topic declared in the relevant module. I opted for this. The annoying exception is for the md5 topic, this module is loaded dynamically at runtime, so we need to make sure the topic is declared in advance.

It may be simpler to simply aggregate all nodebug/1 directives in cli.pl or biomake.pl. Or even a separate debug_topics.pl module. YMMV.

**Comment by ihh** [comment]
this works for me

**Comment by JanWielemaker** [comment]
The rationale is that, as the code is compiled, debug/3 calls in the code register the topic.  This requires
`library(debug)` to be loaded before loading code that uses debug/3.   Now you get warnings if you use
`?- debug(topic)` from the command line.  Not if you put it at the start of your source file.

I don't know what is going wrong here, but one option is to add the line below, which will silence
the warning.

```
user:message_hook(debug_no_topic(Topic), _, _).
```
