### ISSUE TITLE
Support for .DELETE_ON_ERROR ?

### ISSUE THREAD

**Issue by tseemann** [evoldoers/biomake#46]
I noticed that `.DELETE_ON_ERROR` is not one of the supported `make` directives.

Any reason?

@sjackman

**Comment by sjackman** [comment]
I would really like `.DELETE_ON_ERROR` too. That and `.SECONDARY` and `.PHONY` are the directives that I make regular use of.

**Comment by sjackman** [comment]
@ihh `.DELETE_ON_ERROR` is super useful. See https://www.gnu.org/software/make/manual/html_node/Special-Targets.html
For example
```Makefile
all: foo

.DELETE_ON_ERROR:

foo:
	false >$@
```
```
❯❯❯ make
false >foo
make: *** [foo] Error 1
make: *** Deleting file `foo'
❯❯❯ cat foo
cat: foo: No such file or directory
❯❯❯ biomake
 false >foo
While building foo: Error 1 executing false >foo
❯❯❯ ls foo
foo
```

**Comment by sjackman** [comment]
`.SECONDARY` is the default behaviour with `biomake`, which I think is great, so no need for that one.

**Comment by sjackman** [comment]
Woohoo! Thanks, Ian! It's like Christmas again! 🎄

**Comment by tseemann** [comment]
Thanks Ian.
