### ISSUE TITLE
Set environment variables with export foo=bar [feature request]

### ISSUE THREAD

**Issue by sjackman** [evoldoers/biomake#50]
A GNU Makefile can set an environment variable like so:
```Makefile
export foo=bar
all:
	sh -c 'echo $$foo'
```
```
❯❯❯ make
sh -c 'echo $foo'
bar
❯❯❯ biomake
Exception: error(syntax_error(GNU makefile parse error at line 1 of file Makefile: export foo=bar),_1650)
```

**Comment by sjackman** [comment]
With GNU Make I use this feature to time each command like so:
```
export SHELL=zsh -opipefail
export REPORTTIME=1
export TIMEFMT=time user=%U system=%S elapsed=%E cpu=%P memory=%M job=%J
```

**Comment by sjackman** [comment]
In the mean time, does `biomake` define a variable that I could use to skip incompatible syntax? For example…
```makefile
ifndef BIOMAKE
export SHELL=zsh -opipefail
export REPORTTIME=1
export TIMEFMT=time user=%U system=%S elapsed=%E cpu=%P memory=%M job=%J
endif
```

**Comment by sjackman** [comment]
GNU Make defines the variable `MAKE_VERSION`, so I can use `ifdef MAKE_VERSION`. Could Biomake please define `BIOMAKE_VERSION`?

**Comment by sjackman** [comment]
Using `ifdef` to skip incompatible syntax doesn't unfortunately work as I had hoped, because `biomake` still parses the text inside the conditional, even when the conditional is false.

**Comment by ihh** [comment]
Shouldn’t be hard to mimic export syntax. Sorry have been inattentive to biomake issues, will take a look at this tomorrow too

**Comment by sjackman** [comment]
Thanks, Ian! While you're looking at `export`, I also occasionally use `override`. e.g.
```
override foo=bar
```
The result is to set `foo` to `bar` even when `foo=ook` is specified on the command line. This issue is low priority for me. The workaround is simply to remove the `override` keyword, which is usually fine.

**Comment by ihh** [comment]
This should work now @sjackman. You could open fresh issues for `override` and/or `unexport` if you decide you do need them.

**Comment by sjackman** [comment]
Thank you, Ian! 🎈
