### ISSUE TITLE
Tag a stable release

### ISSUE THREAD

**Issue by sjackman** [evoldoers/biomake#61]
There's been a number of improvements to Biomake since the last stable release, 0.1.3. Could you please tag a new stable release?

**Comment by ihh** [comment]
@cmungall i think you're the release doctor

**Comment by sjackman** [comment]
@cmungall Is it time for a new release of Biomake, Chris?

**Comment by cmungall** [comment]
0.1.5 tagged

**Comment by sjackman** [comment]
Thanks, Chris!
