### ISSUE TITLE
Consider eliminating the -l option

### ISSUE THREAD

**Issue by ihh** [evoldoers/biomake#70]
The `-l` option ("Iterates through directory writing metadata on each file found") is a little odd, and dates back to the earliest (pre-GNU compatible) version of biomake. I'm not sure what it's for. Do we want to keep it @cmungall? I'm adding in more options through the CLI, and single-character options are at a premium, and I don't think there's a good test for this option anyway(?)

**Comment by cmungall** [comment]
Hmm, it doesn't seem to even work any more. I am happy for you to claim `-l`. We can put back the scan functionality with a longer option name after I have a chance to review the functionality.
