### ISSUE TITLE
Problem with swi-prolog 8?

### ISSUE THREAD

**Issue by samwalrus** [evoldoers/biomake#73]
When I try and run biomake in Swi-prolog 8.1.12 it does not work I only get some stuff from 
Swi-Prolog:

` root@787e0d9980b6:/home# biomake hello.head
swipl: Usage:
    1) swipl [options] prolog-file ... [-- arg ...]
    2) swipl [options] [-o executable] -c prolog-file ...
    3) swipl --help     Display this message (also -h)
    4) swipl --version  Display version information
    4) swipl --arch     Display architecture
    6) swipl --dump-runtime-variables[=format]
                        Dump link info in sh(1) format

Options:
    -x state                 Start from state (must be first)
    -g goal                  Run goal (may be repeated)
    -t toplevel              Toplevel goal
    -f file                  User initialisation file
    -F file                  Site initialisation file
    -l file                  Script source file
    -s file                  Script source file
    -p alias=path            Define file search path 'alias'
    -O                       Optimised compilation
    --tty[=bool]             (Dis)allow tty control
    --signals[=bool]         Do (not) modify signal handling
    --threads[=bool]         Do (not) allow for threads
    --debug[=bool]           Do (not) generate debug info
    --quiet[=bool] (-q)      Do (not) suppress informational messages
    --traditional            Disable extensions of version 7
    --home=DIR               Use DIR as SWI-Prolog home
    --stack_limit=size[BKMG] Specify maximum size of Prolog stacks
    --table_space=size[BKMG] Specify maximum size of SLG tables
    --shared_table_space=size[BKMG] Maximum size of shared SLG tables
    --pce[=bool]             Make the xpce gui available
    --pldoc[=port]           Start PlDoc server [at port]

Boolean options may be written as --name=bool, --name, --no-name or --noname`

This is using the SWI-Prolog docker container latest version. If I load a container for swipl:7.7.25 then biomake works fine.

**Comment by cmungall** [comment]
This seems familiar, I'll take a look later today

**Comment by samwalrus** [comment]
In https://github.com/evoldoers/biomake/blob/master/bin/biomake
There is a line 
`$PATH_TO_ME/swipl_wrap -L0 -G0 -T0 -q -p library=$BIOMAKE_PATH  -g 'assert(biomake_prog("'$0'")),main,halt' -t halt -s $BIOMAKE_PATH/biomake/cli -- "$@"
© 2019 GitHub, Inc.`

What are the -L0 -G0 and -T0? If I take those out it seems to work but I am not sure what they are intending to do..

**Comment by cmungall** [comment]
prior to SWI v8 these set limits on stack/heap. 0 meant no limit. This is
all handled automatically in v8. So yes removing is good. We may want to
retain a script "biomake-swipl7" but I think the canonical one should be v8
