### ISSUE TITLE
Dependency paths longer than 2 nodes unsupported?

### ISSUE THREAD

**Issue by rulatir** [evoldoers/biomake#75]
Steps to reproduce (note two consecutive invocations of biomake):

```bash
git clone https://github.com/rulatir/biomake-bug-demo.git
cd biomake-bug-demo
biomake -H
biomake -H
```

Expected result:

`build/indirectly-dependent` should contain the same random data as `build/random64` because:
 * the former has the latter as a dependency
 * the former is built simply by copying the latter

Actual result:

`build/indirectly-dependent` contains stale data from when it was created as a result of the first invocation of `biomake`.

Output of second invocation:

```
Warning: could not update MD5 file for FORCE <-- []
  dd count=1 if=/dev/urandom of=build/randomstuff
1+0 records in
1+0 records out
512 bytes copied, 0.000138352 s, 3.7 MB/s
 base64 < build/randomstuff > build/random64
build/indirectly-dependent is up to date
```

The claim that `build/indirectly-dependent` is up to date is patently false. Its dependency has changed.

**Comment by rulatir** [comment]
BOOMP?

**Comment by cmungall** [comment]
Apologies for the delay, I have a fix that unfortunately causes one of the tests to fail, will look into this later, but for now you could try this branch: https://github.com/evoldoers/biomake/tree/issue-75

**Comment by ihh** [comment]
@cmungall could you add a test to your PR that includes the bug that this fixes. I will look at the test that now fails.
