### ISSUE TITLE
Rename project to biomake

### ISSUE THREAD

**Issue by cmungall** [evoldoers/biomake#9]
- [x] rename github repo
 - [x] delete old pack on swipl and publish new one

**Comment by ihh** [comment]
renaming the repo is easy, just go to https://github.com/cmungall/plmake/settings

not sure what's involved in publishing a swipl pack

**Comment by cmungall** [comment]
we can also move the repo to an org

**Comment by ihh** [comment]
could do that too. gmod?

**Comment by cmungall** [comment]
+1 

are you an admin or should we contact scott?

**Comment by cmungall** [comment]
To release using the swipl pack system, the easiest way is to use github releases. Should we use semantic versioning, start from `0.1.0` and have the convention of naming the release starting with a `v`, e.g. `v0.1.0`?

**Comment by ihh** [comment]
Sounds good to me

**Comment by ihh** [comment]
Are we ready for release v0.1.0 now? I think so...

**Comment by cmungall** [comment]
OK, I went for it: https://github.com/evoldoers/biomake/releases/tag/v0.1.0 - but go ahead and make any further releases as you like. Once I re-register the new name with swipl these will auto-propagate there.
